// AUTO-GENERATED — DO NOT EDIT.
// Generated by Dagger TypeScript SDK introspector (cmd/codegen generate-entrypoint).

import { Context, Error as DaggerError, FunctionCachePolicy, TypeDefKind, connection, dag, getRegisteredClass } from "@dagger.io/dagger"
import * as __dagger from "@dagger.io/dagger"
import * as telemetry from "@dagger.io/dagger/telemetry"
import { DatalatheClientJava } from "./src/index"

// Load a core/dependency object from its ID via node(id:) and wrap it in the
// matching generated client class. Mirrors the SDK runtime loader; replaces the
// retired load<Type>FromID API (removed in #12041). Some core type names
// collide with JS builtins and get a trailing "_" (e.g. "Module" -> Module_).
function __loadCoreObject(id: string, typeName: string): any {
  const cls =
    (__dagger as any)[typeName] ?? (__dagger as any)[typeName + "_"]
  if (!cls) {
    throw new Error(`generated client class not found for core type: ${typeName}`)
  }
  return new cls(new Context().selectNode(id, typeName))
}

function formatError(e: unknown): DaggerError {
  if (e instanceof Error) {
    let error = dag.error(e.message)
    const ext = (e as { extensions?: Record<string, unknown> }).extensions
    if (ext) {
      for (const [k, v] of Object.entries(ext)) {
        if (v !== "" && v !== undefined && v !== null) {
          error = error.withValue(
            k,
            JSON.stringify(v) as string & { __JSON: never },
          )
        }
      }
    }
    return error
  }
  try {
    return dag.error(JSON.stringify(e))
  } catch {
    return dag.error(String(e))
  }
}

function rebuildDatalatheClientJava(state: any): DatalatheClientJava {
  const __obj = Object.assign(Object.create(DatalatheClientJava.prototype), state ?? {})
  if (state) {
    if (state["clientSource"] !== undefined && state["clientSource"] !== null) {
      __obj["clientSource"] = __loadCoreObject(state["clientSource"], "Directory")
    }
  }
  return __obj
}

async function serializeDatalatheClientJava(__obj: DatalatheClientJava): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  if ((__obj as any)["clientSource"] !== undefined && (__obj as any)["clientSource"] !== null) {
    __state["clientSource"] = await ((__obj as any)["clientSource"]).id()
  }
  return __state
}



async function register(): Promise<string> {
  let mod = dag.module_()
  let obj_DatalatheClientJava = dag.typeDef().withObject("DatalatheClientJava", { sourceMap: dag.sourceMap("src/index.ts", 6, 14) })
  obj_DatalatheClientJava = obj_DatalatheClientJava.withFunction(dag.function_("integration", dag.typeDef().withKind(TypeDefKind.VoidKind).withOptional(true)).withDescription("Workspace check: the full chip-lifecycle integration suite against an\nephemeral engine + chip-manager built from the pinned datalathe-backend.").withSourceMap(dag.sourceMap("src/index.ts", 19, 9)).withCheck())
  obj_DatalatheClientJava = obj_DatalatheClientJava.withConstructor(dag.function_("", obj_DatalatheClientJava).withArg("ws", dag.typeDef().withObject("Workspace").withOptional(true), { sourceMap: dag.sourceMap("src/index.ts", 9, 15) }))
  mod = mod.withObject(obj_DatalatheClientJava)
  return await mod.id()
}

async function invoke(
  parentName: string,
  fnName: string,
  parentJson: any,
  args: Record<string, any>,
): Promise<any> {
  switch (parentName) {
    case "DatalatheClientJava": {
      switch (fnName) {

        case "": {
          const __arg_ws = args["ws"] === undefined || args["ws"] === null ? args["ws"] : __loadCoreObject(args["ws"], "Workspace")
          const __result = await new DatalatheClientJava(__arg_ws) as unknown as DatalatheClientJava
          return await serializeDatalatheClientJava(__result)
        }

        case "integration": {
          const __parent = rebuildDatalatheClientJava(parentJson)
          const __result = await __parent.integration()
          return __result
        }
        default:
          throw new Error(`unknown function ${fnName} on DatalatheClientJava`)
      }
    }
    default:
      throw new Error(`unknown object ${parentName}`)
  }
}

async function dispatch() {
  await connection(async () => {
    const fnCall = dag.currentFunctionCall()
    const parentName = await fnCall.parentName()

    if (parentName === "") {
      const id = await register()
      await fnCall.returnValue(JSON.stringify(id) as string & { __JSON: never })
      return
    }

    const fnName = await fnCall.name()
    const parentJson = JSON.parse(await fnCall.parent())
    const fnArgs = await fnCall.inputArgs()

    const args: Record<string, any> = {}
    for (const arg of fnArgs) {
      args[await arg.name()] = JSON.parse(await arg.value())
    }

    try {
      const result = await invoke(parentName, fnName, parentJson, args)
      const out = result === undefined || result === null ? "null" : JSON.stringify(result)
      await fnCall.returnValue(out as string & { __JSON: never })
    } catch (e: unknown) {
      await fnCall.returnError(formatError(e))
      process.exit(1)
    }
  }, { LogOutput: process.stdout })
}

dispatch().catch((e) => {
  console.error(e)
  process.exit(2)
})